
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author misha
 */
public class mishasBakeryForm extends javax.swing.JFrame {

    /**
     * Creates new form mishasBakeryForm
     */
    public mishasBakeryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sCookieCostlbl = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        bakeryimg = new javax.swing.JLabel();
        intro1lbl = new javax.swing.JLabel();
        intro2lbl = new javax.swing.JLabel();
        subtotallbl = new javax.swing.JLabel();
        taxlbl = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        subtotalOutputlbl = new javax.swing.JLabel();
        totaloutputlbl = new javax.swing.JLabel();
        taxoutputlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        croissantslbl = new javax.swing.JLabel();
        sconeslbl = new javax.swing.JLabel();
        eclairslbl = new javax.swing.JLabel();
        aPielbl = new javax.swing.JLabel();
        pPielbl = new javax.swing.JLabel();
        cPielbl = new javax.swing.JLabel();
        strudellbl = new javax.swing.JLabel();
        aCroissantlbl = new javax.swing.JLabel();
        shortbreadlbl = new javax.swing.JLabel();
        gCookielbl = new javax.swing.JLabel();
        sCookieInput = new javax.swing.JTextField();
        gCookieInput = new javax.swing.JTextField();
        strudelInput = new javax.swing.JTextField();
        aCroissantInput = new javax.swing.JTextField();
        pPieInput = new javax.swing.JTextField();
        eclairInput = new javax.swing.JTextField();
        aPieInput = new javax.swing.JTextField();
        croissantInput = new javax.swing.JTextField();
        sconeInput = new javax.swing.JTextField();
        cPieInput = new javax.swing.JTextField();
        cost1 = new javax.swing.JLabel();
        cost6 = new javax.swing.JLabel();
        cost2 = new javax.swing.JLabel();
        cost3 = new javax.swing.JLabel();
        cost4 = new javax.swing.JLabel();
        cost5 = new javax.swing.JLabel();
        cost8 = new javax.swing.JLabel();
        cost7 = new javax.swing.JLabel();
        cost9 = new javax.swing.JLabel();
        cost10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlelbl.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        titlelbl.setText("Misha's Bakery");

        bakeryimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbakery.png"))); // NOI18N

        intro1lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        intro1lbl.setText("Please enter the number of each item you would like");

        intro2lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        intro2lbl.setText("to purchase");

        subtotallbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        subtotallbl.setText("Subtotal:");

        taxlbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        taxlbl.setText("Tax (13%):");

        totallbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        totallbl.setText("Total:");

        subtotalOutputlbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        totaloutputlbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        taxoutputlbl.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        croissantslbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        croissantslbl.setText("Croissants");

        sconeslbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        sconeslbl.setText("Scones");

        eclairslbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        eclairslbl.setText("Eclairs");

        aPielbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        aPielbl.setText("Apple Pies");

        pPielbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        pPielbl.setText("Pumpkin Pies");

        cPielbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cPielbl.setText("Cherry Pies");

        strudellbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        strudellbl.setText("Strudel");

        aCroissantlbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        aCroissantlbl.setText("Almond Croissant");

        shortbreadlbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        shortbreadlbl.setText("Shortbread Cookies");

        gCookielbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        gCookielbl.setText("Gingerbread Cookies");

        sCookieInput.setText("0");
        sCookieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCookieInputActionPerformed(evt);
            }
        });

        gCookieInput.setText("0");
        gCookieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCookieInputActionPerformed(evt);
            }
        });

        strudelInput.setText("0");
        strudelInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strudelInputActionPerformed(evt);
            }
        });

        aCroissantInput.setText("0");
        aCroissantInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCroissantInputActionPerformed(evt);
            }
        });

        pPieInput.setText("0");
        pPieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPieInputActionPerformed(evt);
            }
        });

        eclairInput.setText("0");
        eclairInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eclairInputActionPerformed(evt);
            }
        });

        aPieInput.setText("0");
        aPieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPieInputActionPerformed(evt);
            }
        });

        croissantInput.setText("0");
        croissantInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croissantInputActionPerformed(evt);
            }
        });

        sconeInput.setText("0");
        sconeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sconeInputActionPerformed(evt);
            }
        });

        cPieInput.setText("0");
        cPieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPieInputActionPerformed(evt);
            }
        });

        cost1.setText("(2.00$ each)");

        cost6.setText("(3.25$ each)");

        cost2.setText("(2.00$ each)");

        cost3.setText("(3.50$ each)");

        cost4.setText("(2.75$ each)");

        cost5.setText("(2.50$ each)");

        cost8.setText("(16.00$ each)");

        cost7.setText("(3.50$ each)");

        cost9.setText("(17.50$ each)");

        cost10.setText("(20.00$ each)");

        javax.swing.GroupLayout sCookieCostlblLayout = new javax.swing.GroupLayout(sCookieCostlbl);
        sCookieCostlbl.setLayout(sCookieCostlblLayout);
        sCookieCostlblLayout.setHorizontalGroup(
            sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(gCookielbl)
                                .addGap(18, 18, 18)
                                .addComponent(gCookieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(strudellbl)
                                .addGap(18, 18, 18)
                                .addComponent(strudelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(shortbreadlbl)
                                .addGap(18, 18, 18)
                                .addComponent(sCookieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(eclairslbl)
                                .addGap(18, 18, 18)
                                .addComponent(eclairInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(sconeslbl)
                                .addGap(18, 18, 18)
                                .addComponent(sconeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(croissantslbl)
                                .addGap(18, 18, 18)
                                .addComponent(croissantInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(aCroissantlbl)
                                .addGap(18, 18, 18)
                                .addComponent(aCroissantInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cost1)
                            .addComponent(cost6)
                            .addComponent(cost2)
                            .addComponent(cost7)
                            .addComponent(cost5)
                            .addComponent(cost4)
                            .addComponent(cost3)))
                    .addComponent(titlelbl)
                    .addComponent(intro1lbl)
                    .addComponent(intro2lbl)
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cPielbl)
                                    .addComponent(pPielbl)))
                            .addComponent(aPielbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(pPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cost9))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(aPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cost8))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(cPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cost10)))))
                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totallbl)
                            .addComponent(taxlbl)
                            .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(subtotallbl)))
                        .addGap(18, 18, 18)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtotalOutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaloutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sCookieCostlblLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(bakeryimg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        sCookieCostlblLayout.setVerticalGroup(
            sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addComponent(bakeryimg, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cost4)
                                    .addComponent(aCroissantlbl)))
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton1)
                                .addGap(0, 17, Short.MAX_VALUE))))
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addComponent(titlelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intro1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intro2lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shortbreadlbl)
                            .addComponent(sCookieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gCookieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost2)
                            .addComponent(gCookielbl))
                        .addGap(10, 10, 10)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cost3)
                            .addComponent(strudelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(strudellbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aCroissantInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(croissantInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cost5))
                    .addComponent(croissantslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtotallbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subtotalOutputlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(taxoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sCookieCostlblLayout.createSequentialGroup()
                                .addComponent(taxlbl)
                                .addGap(11, 11, 11)))
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totallbl)
                            .addComponent(totaloutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(sCookieCostlblLayout.createSequentialGroup()
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sconeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost6)
                            .addComponent(sconeslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eclairInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost7)
                            .addComponent(eclairslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost8)
                            .addComponent(aPielbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost9)
                            .addComponent(pPielbl))
                        .addGap(12, 12, 12)
                        .addGroup(sCookieCostlblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cPieInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cost10)
                            .addComponent(cPielbl))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sCookieCostlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sCookieCostlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strudelInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strudelInputActionPerformed
        
    }//GEN-LAST:event_strudelInputActionPerformed

    private void gCookieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCookieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gCookieInputActionPerformed

    private void sCookieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCookieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCookieInputActionPerformed

    private void aCroissantInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCroissantInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aCroissantInputActionPerformed

    private void pPieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPieInputActionPerformed

    private void eclairInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eclairInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eclairInputActionPerformed

    private void aPieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPieInputActionPerformed

    private void croissantInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croissantInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_croissantInputActionPerformed

    private void sconeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sconeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sconeInputActionPerformed

    private void cPieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPieInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Shortbread Cookies
        double shortbread;
        shortbread = Double.parseDouble(sCookieInput.getText());
        double shortbreadPrice = shortbread * 2.00;

        //Gingerbread Cookies
        double gingerbread;
        gingerbread = Double.parseDouble(gCookieInput.getText());
        double gingerbreadPrice = gingerbread * 2.00;

        //Strudel
        double strudel;
        strudel = Double.parseDouble(strudelInput.getText());
        double strudelPrice = strudel * 3.50;

        //Almond Croissants
        double aCroissant;
        aCroissant = Double.parseDouble(aCroissantInput.getText());
        double aCroissantPrice = aCroissant * 2,75;

        //Croissants
        double croissant;
        croissant = Double.parseDouble(croissantInput.getText());
        double croissantPrice = croissant * 2.50;

        //Scones
        double scone;
        scone = Double.parseDouble(sconeInput.getText());
        double sconePrice = scone * 3.25;

        //Eclairs
        double eclair;
        eclair = Double.parseDouble(eclairInput.getText());
        double eclairPrice = eclair * 3.50;

        //Apple Pies
        double applePie;
        applePie = Double.parseDouble(aPieInput.getText());
        double applePiePrice = applePie * 18.00;

        //Pumpkin Pies
        double pumpkinPie;
        pumpkinPie = Double.parseDouble(pPieInput.getText());
        double pumpkinPiePrice = pumpkinPie * 17.50;

        //Cherry pie
        double cherryPie;
        cherryPie = Double.parseDouble(cPieInput.getText());
        double cherryPiePrice = cherryPie * 20.00;

        //Outputs
        double subtotal = cherryPiePrice + pumpkinPiePrice + applePiePrice + eclairPrice + sconePrice + shortbreadPrice + croissantPrice + aCroissantPrice + strudelPrice + gingerbreadPrice;
        subtotalOutputlbl.setText(String.valueOf(subtotal)+ " $");
        
        double tax = subtotal * 0.13;
        taxoutputlbl.setText(String.valueOf(tax)+ " $");
        
        double total = subtotal * 1.13;
        totaloutputlbl.setText(String.valueOf(total) + " $");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mishasBakeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mishasBakeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mishasBakeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mishasBakeryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mishasBakeryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aCroissantInput;
    private javax.swing.JLabel aCroissantlbl;
    private javax.swing.JTextField aPieInput;
    private javax.swing.JLabel aPielbl;
    private javax.swing.JLabel bakeryimg;
    private javax.swing.JTextField cPieInput;
    private javax.swing.JLabel cPielbl;
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel cost10;
    private javax.swing.JLabel cost2;
    private javax.swing.JLabel cost3;
    private javax.swing.JLabel cost4;
    private javax.swing.JLabel cost5;
    private javax.swing.JLabel cost6;
    private javax.swing.JLabel cost7;
    private javax.swing.JLabel cost8;
    private javax.swing.JLabel cost9;
    private javax.swing.JTextField croissantInput;
    private javax.swing.JLabel croissantslbl;
    private javax.swing.JTextField eclairInput;
    private javax.swing.JLabel eclairslbl;
    private javax.swing.JTextField gCookieInput;
    private javax.swing.JLabel gCookielbl;
    private javax.swing.JLabel intro1lbl;
    private javax.swing.JLabel intro2lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField pPieInput;
    private javax.swing.JLabel pPielbl;
    private javax.swing.JPanel sCookieCostlbl;
    private javax.swing.JTextField sCookieInput;
    private javax.swing.JTextField sconeInput;
    private javax.swing.JLabel sconeslbl;
    private javax.swing.JLabel shortbreadlbl;
    private javax.swing.JTextField strudelInput;
    private javax.swing.JLabel strudellbl;
    private javax.swing.JLabel subtotalOutputlbl;
    private javax.swing.JLabel subtotallbl;
    private javax.swing.JLabel taxlbl;
    private javax.swing.JLabel taxoutputlbl;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel totallbl;
    private javax.swing.JLabel totaloutputlbl;
    // End of variables declaration//GEN-END:variables
}
